ruxailab/RUXAILAB

src/views/admin/TestListView.vue
Era solicitada uma variável coop que já não existe mais, os usuários novos não conseguiam acessar por conta disso
=> Bug fix test page

.github/workflows/test/test.yml
The github Action does not run because the trigger was not well defined.
=> Fix Github Actions

src/components/molecules/OptionsTable.vue
This PR fixes #435 
The bug seems to happen exclusively for options with no value set, as discussed [here](https://github.com/ruxailab/RUXAILAB/issues/435#issuecomment-2059213309). To figure out why, first let's take a closer look at the `deleteItem` method:
```
deleteItem(item) {
this.options.splice(this.options.indexOf(item), 1)
}
```
Now, my understanding is that if there are multiple items with values as null, indexOf might always return the index of the first item with null value, not necessarily the one we want to delete.
One way to fix this issue is to assign a unique identifier to each item when it is created, and use this identifier to find the correct item to delete. This ensures that even items with identical visible properties can be correctly distinguished. For this, I have …
=> Issue #435: deleting wrong option in heuristic test

src/components/molecules/IntroAnalytics.vue, src/components/molecules/IntroAnswer.vue, src/components/molecules/IntroCoops.vue, src/components/molecules/IntroEdit.vue, src/locales/en.json
This PR addresses the problem documented in issue #453 by updating the Discord link and correcting the typo "comunity" to **community.**
=> fix: typo and broken discord link

README.md, dockerfile
- This pr addresses #360 
1. Ensure Docker is installed on your system.
2. Navigate to the root directory of the project and run:
```bash
docker build -t ruxalab .
```
3. Once the image is built, run it using:
```bash
docker run -d --env-file .env -p 5000:5000 ruxalab
```
4. Visit `http://localhost:5000` in your browser to view the application.
=> dockerfile written for building docker image

src/components/atoms/ModeratedTasks.vue
added rules to the task description
The Final Result
[screen-recorder-tue-jun-18-2024-10-55-20.webm](https://github.com/ruxailab/RUXAILAB/assets/142778969/267036c7-c1f9-4eb5-8ceb-f586d0ff1c64)
=> Fixes #508 Added validation to Task Title and Description

.github/workflows/playwright.yml
=> fix: updated deprecated actions/upload-artifact@v2 to v4

src/components/atoms/NotificationButton.vue, src/components/molecules/NotificationList.vue, src/controllers/UserController.js, src/locales/en.json, src/locales/es.json, src/locales/hi.json, src/locales/pt_br.json, src/models/Notification.js, src/models/UserModel.js, src/router/modules/admin.js, src/views/admin/NotificationPage.vue
#546 
[#546 ](url) 
notification are categeorizes in two section 
A> unread
b> inbox
inbox consist of all the notification user has requested where as 
unread consist of notification which are not read
=> Notification page implemented resolves enhacement request #546 

src/components/molecules/Toolbar.vue
fixed #563 
1. Replaced "font" with "font-family"
2. Added a fallback font-family "sans-serif
=> Fixed the error related to expected CSS shorthand usage and added a generic font-family in src/components/molecules/Toolbar.vue

src/views/admin/DashboardView.vue, src/views/admin/ProfileView.vue, src/views/public/SignUpView.vue
This PR addresses inconsistencies in the password field across the Signup and Update Password pages.
Fixes:
Adds the missing eye icon to the update password field, allowing users to toggle password visibility.
Aligns password rules between Signup and Update Password, ensuring consistency.
Closes #586 
**Before changes-**
**After changes-**
**Additional changes-**
Added orange highlights to make UI more intuitive and user friendly.
=> Fix Design Inconsistencies & Missing Eye Icon in Update Password Field

src/components/atoms/GlobalErrorHandler.vue
The application encountered the following runtime error:  
1. **Direct Access to Vuex State**  
- The original implementation accessed `this.$store.state.error` directly in the `error()` method.  
- When the state was uninitialized or reset, `errorCode` and `message` were `undefined`, causing the error.
2. **Improper Toast Invocation**  
- The Vue Toastification instance (`this.$toast.error`) was used without proper initialization.  
- **Used `mapState` to Bind State Correctly**  
```js
computed: {
...mapState({
error: (state) => state.error,
}),
}
=> fix: "Cannot read properties of undefined (reading '__esModule')" Error

.gitignore, ui-debug.log
while using firebase emulators there is one more debug file that gets created when we create a test which is not included in the .gitignore, this pr adds database-debug.log to .gitignore.
This PR also adds debug-ui.log to .gitignore and also removes ui-debug.log from the codebase.
=> Update .gitignore to ignore databse-debug.log and ui-debug.log

src/locales/es.json, src/locales/hi.json, src/locales/pt_br.json
- Replaced multiple `[TODO]` placeholders with appropriate text.
- Ensured consistency in terminology and UI elements across different sections.
- Updated user-facing texts in alerts, buttons, switches, inputs, and settings.
1. Open the updated sections in the project.
2. Verify that all `[TODO]` placeholders have been replaced with meaningful text.
3. Check for consistency in terminology and UI elements.
These updates improve the user experience by replacing placeholders with clear and accurate text.
=> # Fixes #635: Replaced Multiple [TODO] Placeholders with Meaningful Text

src/views/public/Help.vue
This update replaces the hardcoded copyright year (`© 2025 Ruxailab`) with a dynamic JavaScript property to ensure it updates automatically each year.  
- Replaced hardcoded `2025` with `new Date().getFullYear()` in `src/views/public/Help.vue`.  
- Ensures the footer remains up-to-date without manual changes.  
Fixes #729 
- Verified that the year updates dynamically on page load.  
- No impact on other components.  
Merging this will keep the copyright year updated automatically.
=> [Fix] Use dynamic copyright year

src/components/molecules/HeuristicsTable.vue
📝 What Does this PR Do?
This PR fixes a content overflow issue in the HeuristicsTable component where long question titles were not properly handled in the subheader area. The fix implements a scrollable container for question titles that exceed the designated space.
Fixes #687  
🔄 Changes Made
Updated the styling in `src/components/molecules/HeuristicsTable.vue`
📌 Reason for Change
Previously, when question titles contained multiple lines of text, they would overflow their container, causing layout issues and poor readability. This fix ensures that:
- Question titles remain contained within their designated space
- Users can scroll to read longer titles
✅ Testing
Attaching local Testing video here
https://github.com/user-attachments/assets/d0c4f4a7-c828-4821-9e1c-6d47812cccc1
=> Fixed Question content overflow in Heuristics table sub header

.github/workflows/ishikawa-tools.yml
Closes #690 
Upgraded actions/checkout from v2 to v4 in the General Reports workflow to enhance security, performance, and compatibility with the latest Github Actions features. This improves repository checkout efficiency.
=> Upgrade actions/checkout from v2 to v4 in the General Reports workflow.

src/router/index.js
This PR addresses a security issue where unauthorized users were able to access the `/testslist` route by clicking on the `R` logo on the signup page. This unintended behavior has been fixed to ensure proper route restrictions.
Fixes #693 
- Removed the `from` check in the router, which was identified as the root cause of the bug.
Unauthorized users were granted access to the `/testslist` route, which posed a security risk. This fix ensures that routing behaves as intended, maintaining proper access control.
Verified in the development environment that the routing now works as expected. Clicking the `R` logo correctly redirects users to the homepage instead of the `/testslist` route.
=> fix: users were able to visit /testslist when on signup page

src/controllers/AuthController.js
Fix the `autoSignIn` method in the `AuthController` class. Corrects a typo in the `reject` parameter and adds error handling to ensure the promise is properly rejected if an error occurs during the authentication state change.
* [`src/controllers/AuthController.js`](diffhunk://#diff-2b7f056f0df4dbe688dbd457184c1516c3f511526c974193ad24749d12d37a1aL31-R41): Corrected the typo in the `reject` parameter and added error handling to the `autoSignIn` method.
Notes:
fix typo in the Promise parameter from rejecj to reject.
Added a proper error handler to the onAuthStateChanged method, this is what it does: Calls unsubscribe() (prevent memory leaks), and properly rejects the promise with the error
=> Fix: Replace typo + Add error handler in AuthController.js 

README.md
This PR corrects the comment format in the `.env` section of the README file. Previously, comments were incorrectly formatted using `//`, which is not valid for `.env` files. The correct format (`#`) has now been applied.  
Fixes #683  
- Updated the `.env` example in the README to use `#` for comments.  
- Changed syntax highlighting from `javascript` to `ini` for better readability.  
- `.env` files do not support `//` comments.  
- Improves clarity for new contributors setting up the project.  
- Manually reviewed the changes in the README file.
=> docs: Correct comment format in .env section of README

README.md
Issue
The version requirements mentioned in README.md file under system setup, are outdated and does not work with latest systems, the documentation for setting up .env file is also outdated and does not work in accordance with firebase's latest update where link for real-time database is not added automatically in firebase sdk. Also no mention of the requirement that we have to uncomment some lines under src/index.js to make the emulators run.
Also you have to set your folder name as weight_function for firebase functions to work and in the documentation it's mentioned as '(chose your option)'.
Solution
After successfully setting up the project locally, i updated the readme.md file's version requirements to latest version which work and also added missing parts of the documentation like …
=> Updated README.md to reflect latest versions of dev env and clear instructions #646

.github/workflows/sonarcloud_issue_creator.yml
Updated GitHub Actions workflow to allow manual execution via `workflow_dispatch`.
- Replaced `workflow_run` trigger with `workflow_dispatch` for manual execution.  
- Ensured dependencies are installed before running the script.  
- Feature: [#566]
- Previous PRs: [#725 , #748]
1. Go to **GitHub → Actions**.  
2. Select **SonarCloud Issue Creator** workflow.  
3. Click **Run workflow**, choose the branch, and start the run.
=> Updated GitHub Actions workflow to allow manual execution via `workflow_dispatch`

src/components/atoms/QuestionHelpBtn.vue
1. Replaced the deprecated v-slot:activator="{ on, attrs }" syntax  with v-slot:activator="{ props }" in the tooltip.
2. Bound props directly to <v-btn> instead of using v-bind="attrs"  and v-on="on".
3. Ensures compatibility with Vuetify v3 and prevents potential  breaking issues.
=>  Fix: Update deprecated Vuetify slot syntax in tooltip activator

src/components/atoms/TipButton.vue
1. Removed required: true from the task prop since a default object  is already provided.
2. Replaced the traditional function with an arrow function for better  readability.
3. This fix ensures Vue does not throw a warning when the task prop  is missing. No breaking changes; behavior remains the same.
=> Fix default prop handling in task object

src/components/molecules/FeedbackView.vue
previous state the tooltip was missing 
also link open as blank if moderator doesnt provide the link 
Added ToolTips in Live test and also added a validation In case the link in empty
=> Added ToolTips in LiveTest to remove confusion

src/components/atoms/FormPostTest.vue, src/components/atoms/UserVariables.vue, src/components/organisms/EditModeratedUserTest.vue
This PR addresses issue #642 , where the Moderator Edit test was not responsive on all devices. The existing form layout was conflicting between desktop and mobile/tablet views.
- Created a new template specifically for mobile and tablet devices to ensure proper alignment.
- Separated the desktop form structure to prevent conflicts.
- Applied media queries and flexible CSS properties (`flexbox`, `grid`) for better responsiveness.
- Ensured consistency across various screen sizes.
1. Open the Moderator Edit test on different devices (mobile, tablet, desktop).
2. Verify that the layout adapts correctly without breaking.
3. Check if the form elements align properly on all screen sizes.
**Before:**  
[Screencast from 07-03-25 11:21:19 PM …
=> Fix Responsiveness of Moderator Edit Test ( #642)

src/components/molecules/HeuristicsSenttings.vue, src/locales/en.json, src/locales/es.json, src/locales/hi.json, src/locales/pt_br.json
Added validation to prevent uploading empty CSV files. Before processing, the code trims the CSV content and checks if it is empty. If empty, an error message is displayed, and execution stops.
- Trimmed the CSV content (`.trim()`) before processing..  
- If the file is empty, an error message (`this.errorMessage = this.$t('HeuristicsSettings.messages.emptyCsvFile')`) is displayed. 
- Stopped execution to prevent further processing. 
- Added error message: `"emptyCsvFile": "The CSV file is empty. Please provide a file with data."` 
Fixes #733 
- Attempted to upload an empty CSV file → Proper error message displayed.  
- Uploaded a valid CSV file → Processed successfully without issues.
=> Fix: Add validation to prevent empty CSV file upload

src/components/atoms/Snackbar.vue
1. Updated watch.snackMessage() to use the newVal parameter 
instead of calling this.snackMessage again.
2. This improves efficiency by preventing duplicate computed 
property calls.
3. No changes in functionality—just a performance improvement.
No breaking changes; the component behavior remains the 
same.
Why This Change Matters?
🔹 Improves performance by avoiding unnecessary reactivity 
updates.
🔹 Ensures Vue evaluates snackMessage only once per update.
🔹 Keeps the code cleaner and more readable.
=> Optimize watcher for snackMessage to avoid redundant calls

package.json
Fix error when running Playwright npm command: 
```
Error: Cannot use --browser option when configuration file defines projects. Specify browserName in the projects instead.
```
Since `browser` options are configured in `playwright.config.js`, calling Playwright with browser flag gives an error. Remove the flag fixes this. 
Add `test-playwright-ui` command to help debugging.
=> [FIX] Remove browser flag and add ui command for Playwright

src/components/dialogs/CreateTestUserDialog.vue
This PR fixes a bug where **userTestType** (e.g., **'moderated' or 'unmoderated'**) was not being reliably stored in **Firestore** due to inconsistent casing in the **setType** method inside **CreateTestUserDialog.vue**.
**Fixes #792** 
Normalize type to lowercase before setting it in **test.userTestType**.
User Test creation would occasionally miss **userTestType**, breaking the edit page.
Here is a screen recording showing the issue when creating a User Test:
https://github.com/user-attachments/assets/0e36836d-fd9a-4278-9f43-c9ca029590ca
**userTestType** is always stored as **lowercase** (**'moderated' or 'unmoderated'**) correctly.
https://github.com/user-attachments/assets/fe9bcf18-3943-44ef-9696-6fd76420ea4d
**User Test edit** pages now load as expected.
=> fix: ensure userTestType is stored with normalized casing

src/components/molecules/IntroEdit.vue
Refactor: Moved items from a computed property to data since it's a static array that doesn't depend on reactive state. This improves clarity, avoids unnecessary dependency tracking, and aligns better with Vue's design principles.
In the original code, items was defined as a computed property:
computed: {
items() {
return [/* static array */]
}
}
What are computed properties for?
* computed properties are typically used when:
* You want to derive data from other reactive data (like props, data, or store).
* You want that derived data to automatically update when the dependencies change.
Why is this an issue here?
* The items list is not derived from any reactive state.
* It is static — its values do not change unless the code changes.
* Using computed here is unnecessary overhead — Vue …
=> 🔧 Improvement: Move items from computed to data

src/components/dialogs/CreateTestNameDialog.vue
Fixed issue #663 in the CreateTestNameDialog component where the v-model='isOpen' was directly bound to a prop. In Vue, props should not be modified directly inside a component. To resolve this, I replaced the v-model with :value and input, emitting an update:isOpen event to ensure proper one-way data flow and avoid mutating the prop directly.
=> BUG: v-model=IsOpen - fixed

src/components/organisms/EditModeratedUserTest.vue, src/locales/en.json, src/locales/es.json, src/locales/hi.json, src/locales/pt_br.json
fixes #826 
Added all the lost strings for the moderated test with English, Spanish, Portuguese translation
=> fix(user-testing): Added all the lost strings for Moderated Test

src/components/atoms/UserVariables.vue
This PR adds the ability to edit the title of pre-form questions directly within the expansion panel. Previously, only the description and selection fields were editable, but the title couldn't be modified after creation.
Before : 
After : 
Closes #872
=> Make Pre-form Question Titles Editable

src/components/atoms/FormPostTest.vue
This PR adds the ability to duplicate questions in the post-test form, which improves efficiency when creating multiple similar test questions.
* Added a duplicate button with a copy icon beside the delete button in each question panel
* Implemented a `duplicateItem` method that creates a deep copy of an existing question
* The duplicated question is inserted immediately after the original with "(copy)" added to its title
* The state is automatically saved after duplication
[https://github.com/user-attachments/assets/5d750e33-bc9f-4c95-8f11-8e02b7cfb996](https://github.com/user-attachments/assets/5d750e33-bc9f-4c95-8f11-8e02b7cfb996)
Closes #874
=> Add question duplication feature to post-test form

e2e/createHeuristicTest.spec.js
This Pull Request adds a suite of automated UI tests to the RUXAILAB platform using **Playwright**, targeting the process of creating heuristic evaluation tests.
---
To improve automated test coverage by implementing a robust test case that validates the test creation feature from different user interaction scenarios. This ensures the form behaves correctly with both valid and invalid inputs.
---
This test case includes **five distinct test runs**, covering a variety of user flows related to heuristic test creation:
- Fills in both name and description.
- Confirms the test is created by searching for its title (`Test successful`) in the UI and clicking it.
- Leaves the description blank.
- Still submits the test and confirms its presence in the list using the test name (`Test without …
=> test: add heuristic test creation scenarios
