src/controllers/TestController.js
src/views/admin/ManagerView.vue

some fixes at the test cards design and the creation of a controllers folder with Test, Template, User and Auth controllers not finished.

finalization of [M1] plus begin of controllers page

---

src/api/modules/database.js
src/components/atoms/AddOptionBtn.vue
src/components/atoms/IntrosComponent.vue
src/components/molecules/IntroEdit.vue
src/components/molecules/OptionsTable.vue
src/controllers/AuthController.js
src/controllers/HeuristicController.js
src/controllers/TemplateController.js
src/controllers/TestController.js
src/controllers/UserController.js
src/store/modules/database/tests.js
src/views/admin/TestListView.vue

missing the Auth controller - need enums and models.

Controllers

---

src/router/tools.js
src/store/modules/newStores/Auth.js
src/views/public/LandingPageView.vue
src/views/public/SignInView.vue
src/views/public/SignUpView.vue

Reverts uramakilab/remote-usability-lab#94

Revert "Manage test"

---

src/components/atoms/NotificationButton.vue
src/controllers/UserController.js
src/views/admin/CooperatorsView.vue

Notifications bug

---

src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/admin/DashboardView.vue

DashboardView translated

---

src/components/organisms/LandingAbout.vue

button is now redirecting to the retlab repository

See the code btn fixed

---

src/components/organisms/UserAnalytics.vue
src/views/public/TestView.vue
src/views/public/UserTestView.vue

Succesfully made webcam record in test and in analytics

Webcam record

---

src/router/index.js
src/router/tools.js
src/views/admin/ManagerView.vue

router fixed

---

src/components/organisms/UserAnalytics.vue
src/controllers/TestController.js
src/views/public/UserTestView.vue

Successfully made audio record on user test

feat: made audioRecord

---

src/components/atoms/LeaveAlert.vue
src/components/molecules/HeuristicsTable.vue
src/components/molecules/OptionsTable.vue
src/components/organisms/EditHeuristicsTest.vue
src/views/admin/EditTestView.vue

Successfully showing save modal, when you leave without saving the test.

fix: save modal dont work

---

src/components/atoms/AudioRecorder.vue
src/components/atoms/FormTask.vue
src/components/atoms/ScreenRecorder.vue
src/components/atoms/Timer.vue
src/components/atoms/TipButton.vue
src/components/atoms/VideoRecorder.vue
src/components/molecules/ListTasks.vue
src/components/organisms/EditUserTest.vue
src/components/organisms/UserAnalytics.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/models/UserTask.js
src/store/modules/Answer.js
src/views/public/UserTestView.vue

componentize the new features of tasks

Components user test

---

package-lock.json
package.json
src/components/atoms/AddDescBtn.vue
src/components/atoms/AddOptionBtn.vue
src/components/atoms/FormPostTest.vue
src/components/atoms/ModeratedTasks.vue
src/components/atoms/UserConsent.vue
src/components/atoms/UserVariables.vue
src/components/molecules/ImportCsvTable.vue
src/components/molecules/OptionsTable.vue
src/components/molecules/VideoCall.vue
src/components/organisms/EditModeratedUserTest.vue
src/components/organisms/EditUserTest.vue
src/store/modules/Test.js
src/views/admin/CreateBlankView.vue
src/views/admin/EditTestView.vue
src/views/public/ModeratedTestView.vue
src/views/public/TestView.vue

Moderated Tests design, test view, and edit view design and CRUD

Moderated tests

---

src/components/atoms/FormTask.vue
src/components/atoms/Introduction.vue
src/components/atoms/ModeratedTasks.vue
src/components/atoms/Timer.vue
src/components/atoms/TipButton.vue
src/components/molecules/FeedbackView.vue
src/components/molecules/ImportCsvTable.vue
src/components/molecules/ListTasks.vue
src/components/molecules/TemplateInfoDialog.vue
src/components/molecules/VideoCall.vue
src/components/molecules/WeightTable.vue
src/components/organisms/Footer.vue
src/components/organisms/GeneralAnalytics.vue
src/components/organisms/HeuristicsAnalytics.vue
src/components/organisms/HeuristicsTestAnswer.vue
src/components/organisms/ShowInfo.vue
src/components/organisms/UserAnalytics.vue
src/store/modules/Test.js
src/views/admin/CreateBlankView.vue
src/views/admin/CreateFromTemplateView.vue
src/views/admin/EditTestView.vue
src/views/admin/FinalReportView.vue
src/views/admin/ManagerView.vue
src/views/public/ModeratedTestView.vue
src/views/public/SignInView.vue
src/views/public/TestView.vue
src/views/public/UserTestView.vue

Moderated Test latest branch to implement Video call, with others fixes

Video call

---

src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/store/modules/Auth.js

Wrote auth error's i18n translations.
Related Issue: #318

fix: i18n translations for auth errors

---

firebase.json
firestore-debug.log
src/components/atoms/FinalReportSelectionBox.vue
src/firebase/index.js
storage.rules

I've removed some hardcoded urls that were in the app.

fix: fixed hardcoded urls across app

---

src/components/molecules/Toolbar.vue
src/views/public/SignInView.vue
src/views/public/SignUpView.vue

fix: add`go to home` btn on signin and signout page

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

This PR introduces a `.vscode/extensions.json` file to the project, aimed at recommending the Vetur extension for Visual Studio Code users working on this Vue.js project. It addresses #343 
- Created a `.vscode` directory at the root of the project (if it didn't already exist).
- Added an `extensions.json` file within the `.vscode` directory.
- Specified `"octref.vetur"` as a recommended extension in `extensions.json`, encouraging contributors to install Vetur for enhanced Vue.js development support in VS Code.
- The extension that is recommeded supports vue version 2 .
- The official docs recommend volar ( vue 3 ) which even works for vue 2 but for vue vesions lesser than 2.6.14 , some configs need to change 
- [Extension page](https://marketplace.visualstudio.com/items?itemName=Vue.volar …

Added vscode extension recommendation

---

src/views/public/Help.vue

The PR resolves the issue #345 . Here's a brief look into it with the changes made for the responsive design.
> Before 
https://github.com/ruxailab/RUXAILAB/assets/110292494/3cfb3da8-f7f5-44cf-ab8f-6f86ec537894
> After
https://github.com/ruxailab/RUXAILAB/assets/110292494/47c937d9-4ad0-417b-bacb-553f67dd929a

Enhancements in Help.vue FAQs section

---

src/router/index.js

#332 issue fixed
Now the signup/signin pages will be
redirect to previous pages After a user login and try to go the URLs /signup and /signin.

#332 issue fixed.  (login/signup page issue)

---

src/components/atoms/GlobalErrorHandler.vue
src/store/modules/Auth.js
src/store/modules/Cooperators.js
src/store/modules/Database.js
src/store/modules/Reports.js
src/store/modules/Template.js
src/store/modules/newStores/Database.js
src/views/admin/ManagerView.vue
src/views/admin/ReportView.vue
src/views/admin/TemplateView.vue
src/views/superAdmin/SuperAdminView.vue

Related issue: #367 
Replaced `setError` with new error fields {errorCode, message} globally.
Tested all error messages.
Please review all changes and let me know if any changes are required.
Thanks :)

feat: errorhandler implemented globally

---

README.md

Firebase Config Documentation Update

---

.github/depenadabot.yml

This PR Fixes:
-  #377 
**Motivation:**
The motivation behind this feature request is to ensure that our project's dependencies are regularly updated to include security patches, bug fixes, and new features. Dependabot will automate the process of monitoring and updating dependencies, reducing the manual effort required to keep our project up-to-date.
**Feature:**
1. Dependabot will periodically check for updates to our project's dependencies.
2. When updates are available, Dependabot will create pull requests to update the dependencies in our project.
3. We can review and merge these pull requests to incorporate the latest dependency versions into our project.

Add Support for Dependabot for Automated Dependency Update

---

tests/test-utils.js
tests/unit/AddOption.spec.js

Test that validate Add Option Component.

Add Option Test

---

src/components/atoms/Introduction.vue

This PR is for issue #371 i have added Image Preloading to enhance the performance of our web application. Image Preloading is a technique used to load images in the background before they are actually needed. By Preloading images, It ensure that they are immediately available when requested, resulting in a smoother user experience.

css:added preload for better performance

---

.github/workflows/ishikawa-tools.yml
ishikawa_tools/ishikawa_tools_script.py
ishikawa_tools/requirements.txt

In this PR I changed back to using the auto generated GITHUB_TOKEN (from testing on a fork this should work). I've also edited the user and project secrets to ruxailab and RUXAILAB repectivly and added a workflow_dispatch trigger to the action so that it can be tested more easily.

Ishikawa tools

---

.github/workflows/test.yml
tests/unit/SignIn.spec.js

Generate a message in the pull request and in discord when a test fails.

472 generate message when test failed [TO SOLVE]

---

src/components/molecules/HeuristicsTable.vue

… axis #480
issue mentioned by marc about wrong align of icon : mdi-chevron-right

fix(heuristics): heuristic items are not properly aligned on vertical…  ISSUE #480

---

src/components/atoms/FormTestDescription.vue
src/components/molecules/HeuristicsTable.vue
src/views/admin/SettingsView.vue

Code added 
settingview.vue
changed 100 to 200 words
line 51
line 212 
added validation Title Code
line 287
check file on igrone whitespaces to see the changes 
i dont know why it says added +577 
if you know please tell me it will help me in long run

Resolves #505 Title Validation added 

---

src/components/atoms/FormPostTest.vue
src/components/atoms/UserVariables.vue

View Changes i Made on remove empty space to see the changes i have made

Fixes [🐞 BUG]: NO restriction on creating empty Variable in Preform #510

---

src/views/admin/SettingsView.vue

Resolves #518 part 2 form validation error

Fixes [🐞 BUG]: Issues in creating Template #518 template form validation

---

src/views/public/TestView.vue

#520  Created Submit-Page with defined Logic

Resolves #520 Submit Page for Heuristics Test

---

src/components/organisms/HeuristicsTestAnswer.vue

Resolves [✨ FEATURE]: Export Evaluator Answer Table As Csv #502

---

src/components/atoms/AudioRecorder.vue
src/components/atoms/AudioVisualizer.vue
src/views/public/UserTestView.vue

#536 
added audio visualization when microphone is recording
[screen-recorder-sun-oct-06-2024-16-34-48.webm](https://github.com/user-attachments/assets/73f51e25-0610-4ac7-ae03-a868545106af)

Resolves #536 microPhone audio visualization

---

src/views/admin/ProfileView.vue

In the Last PR #583 @amishhaa added the updatePassword function two times in `src/views/admin/ProfileView.vue` file 
due to this the application is unable to start and it is breaking.

fix: Fixed the double import of updatePassword function causing the code to break

---

.github/workflows/test.yml

Updated the deprecated version of actions/checkout and actions/cache to the latest version.
So, now the test.yml workflow will work perfectly.

fix: Updated the deprecated version of actions/checkout and actions/cache

---

src/components/molecules/Toolbar.vue
src/controllers/UserController.js
src/models/UserModel.js
src/views/admin/ProfileView.vue

fixed #592 
1. Optimized the code of `ProfileView.vue` to use UserController functions.
2. Move Firebase-related methods to a dedicated UserController
3. Retrieving user data as a computed property from the firestore DB.
4. Created new fields in `users` collection to updated and delete user info.
ProfileView working
[Screencast from 2025-02-14 01-29-00.webm](https://github.com/user-attachments/assets/29725e1c-ad5d-4a0f-9da3-f483b0eea5b1)
firestore DB saving data
[Screencast from 2025-02-19 20-17-25.webm](https://github.com/user-attachments/assets/78b4a256-6cdf-4c10-9c87-60d2722b04da)

feat: Updated ProfileView to use usercontroller and added the complete functionality to perform Backend operations

---

src/views/public/TestView.vue

- **Removed background image** and placed it inside a separate `<v-col>` to enhance visibility and improve layout structure.  
- **Adjusted title, description, and button alignment**:  
- **Large screens (`lg`)**: Positioned towards the left edge for better readability.  
- **Medium & small screens (`md`, `sm`, `xs`)**: Center-aligned for improved visibility.  
- **Fixed unintended hover effect**, which was automatically introduced due to previous style changes.  
- **Optimized image size and space occupation**, ensuring proper scaling and positioning across different views.  
- **Maintained a clean and structured appearance**, ensuring a consistent look and feel across all screen sizes.  
Here are the before page visibility before and after changes
<br>
**Before Changes**
<br>
**After …

Improve responsiveness of User Test Preview with a cleaner layout

---

src/views/admin/ProfileView.vue

**Description:**
This pull request introduces a number of exciting improvements to the user profile page to enhance its functionality and user experience.
Fixes #624 
**ScreenShot:**
[Screencast from 04-03-25 09:18:20 PM IST.webm](https://github.com/user-attachments/assets/087eb1c9-238b-45ed-b4d2-5183c87813c1)

Enhanced Styling of Profile Page

---

src/components/molecules/Toolbar.vue

** Fixes ** : #628  
This PR enhances the profile dropdown in Ruxailab by improving its UI and UX. The changes include:
- Adding a hover effect to make interactions smoother.
- Displaying the user's initial as an icon for a personalized touch.
**Before Enhancement:**  
**After Enhancement:**

Enhanced Profile Dropdown - Added Hover & Username Initial Icon

---

src/views/public/Help.vue

- Changed the button text color to white for better visibility.
- Fixed the redirection issue so that it correctly navigates to "View All Articles" instead of "View All Bugs".
- Updated the styling to ensure consistency.
Closes #679

fix: make 'View All Articles' button text visible 

---

.github/workflows/sonarcloud_issue_creator.yml
sonarcloud_to_github.py

This PR adds a GitHub Actions workflow (`sonarcloud_issue_creator.yml`) that automatically creates GitHub issues based on SonarCloud analysis results. The workflow runs after the Build workflow completes successfully on the `develop` branch, ensuring that any code quality issues detected by SonarCloud are logged as GitHub issues.  
- **Automated Issue Creation:** Detects new issues from SonarQube scans and creates corresponding GitHub issues.  
- **Severity-Based Issue Prioritization:** Categorizes issues based on severity (Critical, Major, Minor).  
- **Added `sonarcloud_issue_creator.yml`** → Triggers after the **Build** workflow completes on `develop`.  
- **Created `sonarcloud_to_github.py`** → Fetches SonarCloud issues and logs them as GitHub issues.  
- **Enhanced Logging** → …

Feat: Automate Issue Creation from SonarCloud Analysis

---

src/views/superAdmin/SuperAdminView.vue

Fixes #571 
implemented Right color theory chips

Added chips for access level implemented Color theory

---

src/store/modules/User.js
src/views/superAdmin/SuperAdminView.vue

Added Ability of superUser to remove/deleteUser

---

.github/workflows/sonarcloud_issue_creator.yml
sonarcloud_to_github.py

The changes from the [fuzailAhmad123:feat-automating-issue-creation-using-sonarqube-ci/cd](https://github.com/fuzailAhmad123/RUXAILAB/tree/feat-automating-issue-creation-using-sonarqube-ci/cd) branch were initially merged into [fuzailAhmad123:develop](https://github.com/fuzailAhmad123/RUXAILAB/tree/develop), but due to a revert and subsequent PR merges, they were not included in  [ruxailab:develop](https://github.com/ruxailab/RUXAILAB/tree/develop). 
- Reapplies the missing changes from [fuzailAhmad123:feat-automating-issue-creation-using-sonarqube-ci/cd](https://github.com/fuzailAhmad123/RUXAILAB/tree/feat-automating-issue-creation-using-sonarqube-ci/cd).
- Ensures the intended updates are properly merged into [ruxailab:develop](https://github.com/ruxailab/RUXAILAB/tree/develop).
1. …

Fix: Added Missing Files Of Automating Issue Creation Via SonarCloud

---

src/controllers/BaseController.js
src/controllers/TestController.js
src/store/modules/Auth.js
src/store/modules/Test.js
tests/unit/Controllers.spec.js
tests/unit/StoreModules.spec.js

* The original version lacked robust error handling, often only having silent error handling with console.logs.
* The existing tests were not adequately verifying the error handling logic.
* Some existing tests did not have the same formatting as the rest of the repository.
* Implemented consistent error handling in BaseController.js and TestController.js to ensure that errors are properly logged and rethrown.
* Created new test file tests/unit/Controllers.spec.js to verify error handling in controllers.
* Created new test file tests/unit/StoreModules.spec.js to verify error handling in store modules.
* Modified tests/unit/StoreModules.spec.js to use a simpler testing approach that focuses on code structure validation.
(this was generated by github copilot, but accurately describes my …

Refactor: Error handling in BaseController.js, TestController.js, Auth.js, Test.js

---

src/views/public/SignInView.vue

Before there was no form validation for signin form, this PR added validation on form submit
It will be submitted only if validation passed.

Validation added for signIn

---

src/assets/WacgAxe.json
src/components/AccessibilityQuiz.vue
src/components/dialogs/CreateTestNameDialog.vue
src/router/modules/public.js
src/views/admin/CreateBlankView.vue
src/views/public/Documentation.vue
src/views/public/Sample.vue
src/views/public/accessibilityTest.vue

accessibility Testing tool
https://github.com/user-attachments/assets/fc483ca9-ff9d-4aac-b0cb-da6157af8e4e

implemented WACG documentation and Manual accessiblity testing Tool 

---

src/components/AccessibilityQuiz.vue

submissions now include this missing parameters .
1. A field is missing to post the screenshot image of the evidence of the problem.
2. It is necessary to add a field per notes or description of the appraiser.
3. Lack of information as to the details of the report in PDF
4. It is necessary to be able to visualize the patterns in two ways (or one by one) or all of the copy.
5. I also see the information, not with the folded tabs, but rather the results without having to click.

Added Enhacements for manual accessibility testing

---

src/components/atoms/AddCommentBtn.vue
src/components/atoms/ImportImage.vue

🎯 Description
This PR addresses issue #798 by fixing the behavior of comments and images on the heuristic page. The changes ensure proper display of comments and images in the heuristic evaluation interface.

fix(heuristic): on heuristic page subsmission

---

src/firebase/index.js
src/views/admin/Choose.vue
src/views/admin/CreateView.vue
src/views/admin/Inspection.vue
src/views/admin/Testing.vue

🚀 Fix and Responsiveness Update
Fixed issue #649
Made the page fully responsive across different screen sizes (mobile, tablet, and desktop)
Improved layout and user experience on mobile devices

Fix responsive pages

---

src/components/molecules/ListTasks.vue

fixed 
[fixed edit.webm](https://github.com/user-attachments/assets/be0a84e1-2a62-46c7-a68d-00ac6d3b8453)

fixes feat: a task must be editable #846

---

src/components/atoms/FormTask.vue
src/components/atoms/LocaleChanger.vue

Fixed the issue , by adding watch field in the script 
https://drive.google.com/file/d/1Lr2AmKevqFJfs7qOpIcBA4DOq9ia_eMg/view?usp=drive_link

Errors on task creation #852

---

src/components/atoms/LocaleChanger.vue

Added proper padding from the top and remove the overlapping in the content for issue #849
added more styles to fix the issue

Fix: Add padding for proper Hindi character display in language selector #849

---

src/views/public/UserTestView.vue

fixed #870 
[Screencast from 2025-05-17 13-25-19.webm](https://github.com/user-attachments/assets/8b29597f-5c10-47ba-95c3-6e5b66a94818)

fix(user-test): Initialization error tooltip appearing when landing on UserTestView fixed

---

src/views/public/UserTestView.vue

fixed #869 
[Screencast from 2025-05-19 21-39-10.webm](https://github.com/user-attachments/assets/29b37fe5-a2c4-48fb-b2bc-bf95980802ed)

fix(user-test): text-fields are now empty after completing a task

---

e2e/signIntest.spec.js

This test suite validates the complete Sign In workflow for the **Ruxailab** platform using Playwright. It ensures proper authentication, error handling, and user experience flows across multiple browsers (Chrome, Firefox, WebKit).
- **Default timeout**: 60 seconds
- **Navigation timeout**: 60 seconds
- **Comprehensive logging**: Console messages, network requests, and responses
- **Cross-browser testing**: Chrome, Firefox, WebKit support
**Purpose**: Validates form validation and error handling for various input scenarios.
**Test Steps**:
- Navigate to Sign In page (`/signin`)
- Verify page loads correctly with proper title
- Test empty form submission
- Test invalid email format submission
**Assertions**:
- ✅ Page title contains "RUXAILAB"
- ✅ Empty form shows "Email is required" error …

SignIn Tests Playwright

---

src/components/molecules/TestInformationCard.vue
src/views/admin/ManualAccessibility/AccessibilityConfig.vue

chore: removed deprecated imports and >>> usage
